version: '3.7'
services:
  vpn:
     image: ubergarm/l2tp-ipsec-vpn-client
     restart: always
     environment:
         - VPN_SERVER_IPV4
         - VPN_PSK
         - VPN_USERNAME
         - VPN_PASSWORD
     privileged: true
     network_mode: "host"
     volumes :
          - /lib/modules:/lib/modules:ro